$(function(){
    $('body').html(addPage.createForm({}).content);
    var $createDiv = $('#create-div');
    setSubmitEvent($createDiv);
    setCaptchaRefresh($createDiv.find('a'), $createDiv.find('img'));
});

/**
 * $container, The container containing the data generated by addPage.createForm.
 */
function setSubmitEvent($container){
    $container.find('button').on('click', function(){
        Ajax.POST({
            url: 'rest/add',
            data:{
                url: $container.find("[name='url']").val(),
                link: $container.find("[name='link']").val(),
                group: $container.find("[name='group']").val(),
                password: $container.find("[name='password']").val(),
                captcha: $container.find("[name='captcha']").val()
            },
            success:function(data, textStatus, jqXHR){
                console.log(data);
            },
            error:function(jqXHR, textStatus, errorThrown){
                console.log(jqXHR);
            }
        });
    });
//        $.ajax({
//            type: 'POST',
//            url: 'rest/add',
//            contentType: 'application/json',
//            data:{
//                url: $container.find("[name='url']").val(),
//                link: $container.find("[name='link']").val(),
//                group: $container.find("[name='group']").val(),
//                password: $container.find("[name='password']").val(),
//                captcha: $container.find("[name='captcha']").val()
//            },
//            success:function(data, textStatus, jqXHR){
//                console.log(data);
//                console.log(textStatus);
//                console.log(jqXHR);
//
//                $container.replaceWith(null);
//                /*
//                $container.replaceWith(addPage.createForm({
//                    url: data.url,
//                    urlError: data.urlError
//                    }).content);
//
//                */
//            },
//            error:function(jqXHR, textStatus, errorThrown){
//                console.log("Error!");
//                console.log(jqXHR);
//                console.log(textStatus);
//                console.log(errorThrown);
//
//            }
//        });
    });
}

/**
 * $el, The element to trigger the refresh action
 * $img, The img element to paste the image on.
 */
function setCaptchaRefresh($el, $img){
    $el.on('click', function(){
        var xhr = new XMLHttpRequest();
        xhr.open('GET', 'rest/captcha', true);
        xhr.responseType = 'arraybuffer';
        xhr.onload = function(e) {
            if (this.response) {
                var byteArray = new Uint8Array(this.response);
                $img.prop('src', "data:image/jpeg;base64," + btoa(String.fromCharCode.apply(null, byteArray)));
            } else {
                $img.prop('src', "img/questionmark.png");
            }
        };
        xhr.send();
    });
}
