$(function(){
    $('#add-section').html(addPage.addForm({}).content);
    var $container = $('#add-container');
    setSubmitEvent($container);
    setCaptchaRefresh($container.find('a'), $container.find('img'));
});

function postInit(){
    var $container = $('#add-container');
    setSubmitEvent($container);
    setCaptchaRefresh($container.find('a'), $container.find('img'));
}

/**
 * $container, The container containing the data generated by addPage.addForm.
 */
function setSubmitEvent($container){
    $container.find('button').on('click', function(){
        Ajax.POST({
            url: 'rest/add',
            data:{
                url: $container.find("[name='url']").val(),
                link: $container.find("[name='link']").val(),
                group: $container.find("[name='group']").val(),
                password: $container.find("[name='password']").val(),
                captcha: $container.find("[name='captcha']").val()
            },
            success:function(data, textStatus, jqXHR){
                postAdd(data, true);
            },
            error:function(jqXHR, textStatus, errorThrown){
                postAdd($.parseJSON(jqXHR.responseText), false);
            }
        });
    });
}

/**
 * $el, The element to trigger the refresh action
 * $img, The img element to paste the image on.
 */
function setCaptchaRefresh($el, $img){
    $el.on('click', function(){
        var xhr = new XMLHttpRequest();
        xhr.open('GET', 'rest/captcha', true);
        xhr.responseType = 'arraybuffer';
        xhr.onload = function(e) {
            if (this.response) {
                var byteArray = new Uint8Array(this.response);
                $img.prop('src', "data:image/jpeg;base64," + btoa(String.fromCharCode.apply(null, byteArray)));
            } else {
                $img.prop('src', "img/questionmark.png");
            }
        };
        xhr.send();
    });
}

function postAdd(response, success){
    $('#add-section').html(addPage.addForm({
        url: response.url,
        urlError: response.urlError,
        link: response.link,
        linkError: response.linkError,
        group: response.group,
        groupError: response.groupError,
        password: response.password,
        passwordError: response.passwordError,
        captchaError: response.captchaError
    }).content);

    postInit();

    if(success){
        if(!$('#info-table').length){
            $('#info-section').html(addPage.infoHeader({}).content);
        }
        $('#info-table').append(addPage.infoRow({
            url: Constant.REST + "/" + response.url,
            link: response.link,
            group: response.group
        }).content);
    }
}
